lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: false
  trainer:
    benchmark: true
    max_steps: 4000000
    accelerator: ddp
    gpus: 0,1
